name: qgrid-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - qgrid
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - ds4n6-lib
  - seaborn
  - untangle
  - pandas-bokeh
  - timesketch-api-client
  - dill
  - gdown
